repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        entry: cd backend && black
        language: python
        minimum_pre_commit_version: 2.9.2
        require_serial: true
        types_or: [ python, pyi ]

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: cd backend && flake8
        language: system
        types: [python]

      - id: run-tests
        name: run-tests
        entry: cd backend && pytest test
        language: system
        types: [python]

  - repo: https://github.com/thoughtworks/talisman
    rev: 'v1.32.0'
    hooks:
      - id: talisman-commit
        entry: cmd --githook pre-commit
