name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
          MYSQL_ROOT_PASSWORD: root_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h localhost" --health-interval=10s --health-timeout=5s --health-retries=5

    env:
      DATABASE_URL: "sqlite:///./bahmni.db"
      JWT_SECRET_KEY: "15c6e7253abfde9f7012e44b8f14320f12e91874"
      JWT_REFRESH_SECRET_KEY: "a161ce62993602724bb8106b715a8179"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run flake8
        run: |
          cd backend
          flake8

      - name: Run tests with coverage
        run: |
          cd backend
          pytest test --cov=app --cov-report=term